config/routes.rb
Rails.application.routes.draw do   
  resources :users
  resources :posts do
    resources :comments, only: [:new, :edit, :create, :destroy]
  end

  resources :sessions, only: [:new, :create, :destroy]

  get "signup" => "users#new", as: :signup
  get "login" => "sessions#new", as: :login
  get "logout" => "sessions#destroy", as: :logout

  root 'posts#index', as: :root
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true, length: {maximum: 240}
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy 

  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true

  default_scope -> { order('created_at DESC') }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  before_save { self.email = email.downcase }
  before_create :create_remember_token
 
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format: {with: VALID_EMAIL_REGEX}
  validates :nickname, presence: true,
                       uniqueness: { case_sensetive: false },
                       length: { maximum: 20 }
  has_secure_password
  validates :password, length: { minimum: 6 }  

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private 
  
  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :signed_in_user
  before_action :fetch_comment, only: [:edit, :update, :destroy]

  def edit
  end

  def new
    @comment = current_user.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    if @comment = current_user.comments.create!(comment_params) 
      redirect_back_or_to @comment.post
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_back_or_to @comment.post
    else
      render :edit
    end
  end

  def destroy
    respond_to do |format|
      if @comment.destroy
        format.html { redirect_to @comment.post }
        kformat.js {}
      end
    end
  end

  private
  def fetch_comment
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :fetch_post, only: [:show, :edit, :update, :destroy]
  before_action :required_login, only: [:edit, :update, :destroy]
  before_action :signed_in_user
  
  def index
    @posts = Post.paginate(page: params[:page])
  end

  def show 
    @comment = current_user.comments.new
  end

  def edit
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was succesfully created" }
      else
        format.html { render :new }
      end
    end
  end

  def update
    if @post.update!(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    respond_to do |format|
      if @post.destroy
        format.html { redirect_to posts_path }
        format.js {}
      end
    end
  end

  private
  def fetch_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :user_id, :title)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase) 
    if user && user.authenticate(params[:session][:password])
      login user
      redirect_back_or_to user    
    else
      flash.now[:error] = "Invalid email/password combination."
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :fetch_user, only: [:show, :edit, :update]
  before_action :required_login, only: [:edit, :show, :update]
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :admin_user, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to @user, notice: "User was succesfully updated" }
        format.js
      else
        format.html { render :edit }
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        login @user
        format.html { redirect_to posts_path, notice: "User was succesfully created" }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    respond_to do |format|
      @user = User.find(params[:id])
      if @user.destroy
        format.html { redirect_to users_path, notice: "User was deleted" }
        format.js {}
      end
    end
  end

  private
  def fetch_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :nickname)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def logout
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    self.current_user = nil
  end

  def redirect_back_or_to(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to login_url, notice: "Please log in."
    end
  end

  def required_login
    redirect_to login_path, notice: "Please log in." unless signed_in?
  end

  def admin_user
    redirect_to root_path unless current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper
  
  #Returns the Gravatar for the given User
  def gravatar_for(user, options = { size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end

end

app/views/comments/_comment.html.erb
<% @post.comments.each do |comment| %>
  <div id="comment-<%= comment.id %>">
    <div>
      <%= gravatar_for comment.user, size: 35 %>
      <%= comment.user.nickname %>
    </div>
    <%= comment.content %>
    <h6>Posted <%= time_ago_in_words(comment.created_at) %> ago.</h6>
    <% if current_user == comment.user || current_user.admin? %>
        |<%= link_to 'Edit', edit_post_comment_url(comment.post, comment) %>
        |<%= link_to 'Delete', [comment.post, comment], method: :delete, data: {confirm: 'Are you sure?'}, remote: true %>
    <% end %>
    <hr>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.hidden_field :post_id %>
    <%= f.text_area :content, placeholder: "Compose new comment..." %>

    <div><%= f.submit "Comment", class: "btn btn-primary" %></div>
<% end %>

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();

app/views/comments/edit.html.erb
<%= render 'form' %>

app/views/comments/index.html.erb
<% @comments.each do |comment|%>
  <div><%= comment.content %></div>
<% end %>

app/views/comments/new.html.erb
<%= form_for @comment do |f| %>
  <%= hidden_field :user_id %>
  <%= f.label :text %>
  <%= f.text_field :content %>
  <%= f.submit "Create" %>
<% end %>

app/views/layouts/_header.html.erb
<div> 
  <% if signed_in? %>
    |<b><%= link_to "Create a new post", new_post_path%></b>
    |U are signed in as: <%= current_user.nickname %>
    |<%= link_to "Profile", current_user %>
    |<%= link_to "All posts", posts_path %>
    |<%= link_to "Settings", edit_user_path(current_user) %>
    |<%= link_to "Users", users_path %>
    |<%= link_to "Log out", logout_path %>
  <% else %>
    <%= link_to "Log in", login_path %>
    <%= link_to "Sign up", signup_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>  

    <div class="main">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
    </div>

    <%= yield %>
      
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.hidden_field :user_id %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :text %>
    <%= f.text_area :content %>

    <%= f.submit "Create" %>
<% end %>

app/views/posts/_post.html.erb
<div class="post" id="post-<%= post.id %>">
  <%= link_to gravatar_for(post.user, size: 45), post.user %>
  <%= post.title %>
    |Posted <%= time_ago_in_words(post.created_at) %> ago.
    |<%= link_to 'Show', post_path(post)%>
  <% if current_user == post.user || current_user.admin? %>
    |<%= link_to 'Delete', post_path(post), method: :delete, data: {confirm: 'Are you sure?'}, remote: true %>
    |<%= link_to 'Edit', edit_post_path(post) %>
  <% end %>
  <hr>
</div>

app/views/posts/destroy.js.erb
$("#post-<%= @post.id %>").remove();

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<% if @posts.any? %>
  <%= will_paginate %>

  <h3>Posts (<%= @posts.count %>)</h3>
  <%= render @posts %>

  <%= will_paginate %>
<% else %>
  <h1>No one post are not created yet!</h1>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <%= hidden_field :user_id %>
  <%= f.label :text %>
  <%= f.text_field :content %>
  <%= f.submit "Create" %>
<% end %>
<%= button_to "Comment", new_comment_path, method: "get" %>

app/views/posts/show.html.erb
<div class="post">
  <div>
    <%= gravatar_for @post.user %>
    <%= @post.user.nickname %>
  </div>
  <div>
    <strong><%= @post.title %></strong>
  </div>
  <textarea disabled class="content"><%= @post.content %></textarea>
  <% if current_user == @post.user || current_user.admin? %>
    <%= link_to 'Edit', edit_post_path(@post) %>
    |<%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'} %>
  <% end %>
</div>


<div class="comments">
  <h2> Comments </h2>

  <% if @post.comments.any? %>
      <%= render 'comments/comment' %>
  <% else %>
      Not comments yet
  <% end %>

  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>

</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :nickname %>
        <%= f.text_field :nickname, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <div><%= f.submit "Save changes", class: "btn btn-primary" %></div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div>
  <li id="user-<%= user.id %>">
    <%= gravatar_for user %>
    <%= link_to user.nickname, user %>
    <% if current_user.admin? %>
      | <%= link_to "delete", user, method: :delete, data: { confirm: "Are u sure?" }, remote: true %>
    <% end %>
  </li>
</div>

app/views/users/destroy.js.erb
$("#user-<%= @user.id %>").remove();

app/views/users/edit.html.erb
<h2>Edit profile</h2>

<div class="gravatar_edit">
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">change</a>
</div>

<%= render partial: "form" %>

app/views/users/index.html.erb
<h1> All users</h1>

<%= will_paginate %>

<ul class="users">|
  <%= render @users %>  
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1 id="form"> Sign Up! </h1>

<%= render partial: 'form' %>

app/views/users/show.html.erb
<div><%= gravatar_for @user, size: 70 %></div>
<div><%= @user.nickname %></div>

<% if @user.posts.any? %>
  <h3>Posts (<%= @user.posts.count %>)</h3>
  <ul class="posts">
    <%= render @posts %>
  </ul>
  <%= will_paginate @posts %>
<% else %>
  This users has not any post yet.
<% end %>